Algoritmo "multiplos"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/01/2024
Var
// Seção de Declarações das variáveis 
  x, y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval("Digite dois numeros inteiro: ")
  leia(x)
  leia(y)

  se (x % y = 0) ou (y % x = 0) entao
     escreval("Sao Multiplos")
       senao
      escreval("Não sao multiplos")
  fimse

Fimalgoritmo