Algoritmo "tabuada"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/01/2024
Var
// Seção de Declarações das variáveis 
   i,n: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Deseja a tabuada para qual valor? ")
   leia(n)
   
   para i de 1 ate 10 faca
    escreval(n, " x ",i," = ", n * i)
   fimpara

Fimalgoritmo