Algoritmo "teste_mesa_03"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/01/2024
Var
// Seção de Declarações das variáveis 
  x, y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 100
   y <- 100
   enquanto x <> y faca
     escreva("olha")
     x <- RaizQ(y)
   fimenquanto

Fimalgoritmo