Algoritmo "teste_mesa_desafio_02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/01/2024
Var
// Seção de Declarações das variáveis 
   x,y:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   x <- 2
   y <- 10
   escreval("Olá")
   enquanto x < y faca
     escreval(x, "-",y)
     x <- x * 2
     y <- y + 1
   fimenquanto
Fimalgoritmo