Algoritmo "teste_mesa_desafio_03"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/01/2024
Var
// Seção de Declarações das variáveis 
  x,y,i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 4
   y <- 0
   i <- 0
  enquanto i < x faca
    i <- i + 1
    y <- y + i
    escreva(i)
    escreval(y)
  fimenquanto

Fimalgoritmo