Algoritmo "teste_mesa_02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/01/2024
Var
// Seção de Declarações das variáveis 
   x, y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 2
   y <- 0

   enquanto x < 60 faca
      escreva(y)
      x <- x * 2
      y <- y + 10
   fimenquanto
Fimalgoritmo