Algoritmo "teste_de_mesa_04"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/01/2024
Var
// Seção de Declarações das variáveis 
  x,y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 0
   enquanto x < 5 faca
     y <- x * 3
     escreval(y)
     x <- x + 1
   fimenquanto
   escreval("Fim")
Fimalgoritmo