Algoritmo "teste_de_mesa_05"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/01/2024
Var
// Seção de Declarações das variáveis 
  x, y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 2
   y <- 10
   escreval("ola")
   enquanto x < y faca
      escreval(x , "-",y)
      x <- x * 2
      y <- y + 1
   fimenquanto
Fimalgoritmo