Algoritmo "teste_mesa_exercicio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/01/2024
Var
// Seção de Declarações das variáveis 
   x,y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 100
   y <- 100
   
   enquanto (x <> y) faca
      escreval("olha")
      x <- RaizQ(x)
   fimenquanto

Fimalgoritmo