Algoritmo "teste_mesa_01"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/01/2024
Var
// Seção de Declarações das variáveis 
  x,y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  x <- 5
  y <- 0

  enquanto x > 2 faca
     escreva(x)
     y <- y + x
     x <- x - 1
     //escreval(y)
     //escreval(x, " - ", y)
  fimenquanto

Fimalgoritmo