Algoritmo "vetor_exemplo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/01/2024
Var
// Seção de Declarações das variáveis 
   i: inteiro
   vet : vetor [0..4] de inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 0 ate 4 faca
       vet[i] <- i + 10
       escreval(vet[i])
   fimpara

Fimalgoritmo